name: Workflow Task

on:
  push:
    branches:
      - main

jobs:
  Nested_If_Else:
    runs-on: ubuntu-latest
    steps:
      - name: Check conditions
        run: |
          if [ ${{ github.event_name }} == 'push' ]; then
            if [ ${{ github.event.head_commit.message }} == 'deploy' ]; then
              echo "Deploying the application..."
            else
              echo "Not deploying. Commit message does not contain 'deploy'."
            fi
          else
            echo "Not a push event."
          fi

  Secret_Variable:
    runs-on: ubuntu-latest
    steps:
      - name: Use Secret Variable
        run: echo "My secret token is ${{ secrets.CHECK_1 }}"

  Local_Variables:
    runs-on: ubuntu-latest
    env:
      ENV_STRING: "Hello, Ramesh!"
      ENV_INTEGER: 145
    steps:
      - name: Set Local Variable
        run: |
          NORMAL_STRING="Hello, World"
          NORMAL_INTEGER=4589
          echo "Normal Local String: $NORMAL_LOCAL_STRING"
          echo "Normal Local Integer: $NORMAL_LOCAL_INTEGER"
          echo "Environmental Local String: ${{ env.ENV_LOCAL_STRING }}"
          echo "Environmental Local Integer: ${{ env.ENV_LOCAL_INTEGER }}"

  Global_Variables:
    runs-on: ubuntu-latest
    steps:
      - name: Set Global Variable
        run: echo "MY_GLOBAL_VARIABLE=Hello, Ramesh!" >> $GITHUB_ENV
      - name: Use Global Variable in Step 1
        run: |
          echo "Step 1: ${{ env.MY_GLOBAL_VARIABLE }}"



























